# Welcome to Jekyll!
#

# Site settings
title: Super Ventilagon
description: |
  Un juego electromécanico  
  de código y hardware abierto  
owner: Club de Jaqueo # or company name
first_published: 2015 # if migrating another site, the year of your first publish
email: ventilagon@protocultura.net
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ventilagon.protocultura.net" # the base hostname & protocol for your site
social:
  #twitter: https://twitter.com/<username>
  github: https://github.com/clubdejaqueo/super-ventilagon
  #facebook-official: https://facebook.com/<username>
  #linkedin-square: https://linkedin.com/in/<username>
  #google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
